# Generated by Django 2.1.4 on 2019-01-07 21:21

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del beneficio')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Programa')),
                ('institution', models.CharField(max_length=255, verbose_name='Institución')),
                ('start', models.CharField(max_length=255, verbose_name='Fecha de ingreso')),
                ('end', models.CharField(max_length=255, verbose_name='Fecha de término')),
            ],
        ),
        migrations.CreateModel(
            name='JudiciaryProcessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Número')),
                ('date', models.DateField(max_length=255, verbose_name='Fecha')),
                ('kind', models.CharField(max_length=255, verbose_name='Tipo')),
                ('result', models.TextField(max_length=255, verbose_name='Fallo')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('initials', models.CharField(max_length=255, verbose_name='Iniciales')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('specific_type', models.CharField(choices=[('parlamentario', 'Parlamentario'), ('candidato', 'Candidato')], help_text='Parlamentario o candidato', max_length=255, verbose_name='Tipo de persona')),
                ('birth_date', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico de contacto')),
                ('web', models.URLField(max_length=512, null=True, verbose_name='Link al sitio web personal (o cuenta oficial en redes sociales)')),
                ('declared_intention_to_transparent', models.BooleanField(default=False, verbose_name='¿Desea Ud. transparentar su información política general?')),
                ('circuit', models.CharField(max_length=255, null=True, verbose_name='Circuito al que representa o busca representar')),
                ('period', models.CharField(max_length=255, null=True, verbose_name='¿En qué período legislativo se encuentra actualmente?')),
                ('extra_education', models.TextField(max_length=512, null=True, verbose_name='¿Desea transparentar alguna otra experiencia relevante de formación? Puede escribirlas a continuación')),
                ('intention_to_transparent_work_plan', models.BooleanField(default=False, verbose_name='¿Desea Ud. transparentar su plan de trabajo de diputado(a) o candidato(a)?')),
                ('work_plan_link', models.URLField(max_length=255, null=True, verbose_name="Si respondió 'sí', indique en qué link se puede acceder a su programa de trabajo")),
                ('work_plan_doc', models.FileField(null=True, upload_to='work_plans/%Y/%m/%d/', verbose_name="Si respondió 'sí' pero no tiene su plan de trabajo online, acá tiene la posibilidad de adjuntar el archivo")),
                ('intention_to_transparent_patrimony', models.BooleanField(default=False, null=True, verbose_name='¿Desea Ud. transparentar sus declaraciones de Patrimonio e Intereses')),
                ('patrimony_link', models.URLField(null=True, verbose_name="Si respondió 'sí' por favor indique a continuación el link para acceder a su declaración de patrimonio")),
                ('patrimony_doc', models.FileField(null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name="Si respondió 'sí' pero no tiene su declaración de patrimonio publicada online, acá tiene la oportunidad de adjuntar el archivo")),
                ('existing_interests_declaration', models.BooleanField(default=False, null=True, verbose_name='¿Cuenta ud. con una declaración de intereses actualizada?')),
                ('interests_link', models.CharField(max_length=255, null=True, verbose_name="Si respondió 'sí' por favor indique a continuación el link para acceder a su declaración de Intereses")),
                ('interests_doc', models.FileField(null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name="Si respondió 'sí' pero no tiene su declaración de intereses publicada online, acá tiene la oportunidad de adjuntar el archivo")),
                ('judiciary_declaration', models.BooleanField(default=False, verbose_name='¿Desea Ud. transparentar información sobre los procesos judiciales en los que ha estado involucrado(a)?')),
                ('extra_judiciary_declaration', models.TextField(max_length=255, null=True, verbose_name='¿Se ha visto involucrado en más procesos judiciales?')),
                ('judiciary_link', models.URLField(null=True, verbose_name="Si respondió 'sí', por favor indique dónde se puede acceder a esta información (facilite un link u otro recurso)")),
                ('judiciary_description', models.TextField(null=True, verbose_name='¿Desea agregar comentarios o notas aclaratorias sobre uno o más de los procesos judiciales declarados?')),
                ('reelection', models.BooleanField(default=False, verbose_name='¿Eres actualmente diputado/a?')),
                ('benefits_link', models.CharField(max_length=512, null=True, verbose_name='Por favor, indique dónde es posible acceder al detalle sobre los valores asociados al uso de beneficios (se le sugiere indicar un link donde esté publicado el detalle)')),
                ('eth_080_link', models.URLField(help_text='Link a la planilla 080', null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 080')),
                ('eth_172_link', models.URLField(help_text='Link a la planilla 172', null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 172')),
                ('eth_080_doc', models.FileField(help_text='Link a la planilla 080', null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name='Si su planilla 080 no se encuentra publicada online, puede subir el archivo a continuación')),
                ('eth_172_doc', models.FileField(help_text='Link a la planilla 172', null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name='Si su planilla 172 no se encuentra publicada online, puede subir el archivo a continuación')),
                ('benefits', models.ManyToManyField(null=True, to='indice_transparencia.Benefit')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='indice_transparencia.Party')),
                ('previous_parties', models.ManyToManyField(related_name='ex_members', to='indice_transparencia.Party', verbose_name='¿Ha pertenecido ud. a otros partidos o movimientos políticos?')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cargo')),
                ('institution', models.CharField(max_length=255, verbose_name='Institución')),
                ('start', models.CharField(max_length=255, verbose_name='Fecha de ingreso')),
                ('end', models.CharField(max_length=255, verbose_name='Fecha de término')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='indice_transparencia.Person')),
            ],
        ),
        migrations.AddField(
            model_name='judiciaryprocessrecord',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judiciary_records', to='indice_transparencia.Person'),
        ),
        migrations.AddField(
            model_name='educationalrecord',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_records', to='indice_transparencia.Person'),
        ),
    ]
