# Generated by Django 2.1.4 on 2018-12-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='person',
            name='circuit',
            field=models.CharField(max_length=255, null=True, verbose_name='Circuito'),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_educ',
            field=models.BooleanField(default=False, null=True, verbose_name='¿Publica su formación académica?'),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_educ_detail',
            field=models.TextField(null=True, verbose_name='Detalle de su formación académica'),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_experpol',
            field=models.BooleanField(default=False, null=True, verbose_name='¿Publica su experiencia en otros cargos políticos?'),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_experpol_detail',
            field=models.TextField(null=True, verbose_name='Texto con resumen de su experiencia política previa'),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_experpro',
            field=models.BooleanField(default=False, null=True, verbose_name='¿Publica su experiencia profesional?'),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_experpro_detail',
            field=models.URLField(null=True, verbose_name='Link a CV con detalles.'),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_transfu',
            field=models.IntegerField(default=0, help_text='número de veces que ha cambiado de afiliación política (partido o movimientos)', verbose_name='Transfuguismo'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_080',
            field=models.BooleanField(default=False, help_text='¿publica planilla 080?', verbose_name='Ética presupuestaria / planilla 080'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_080_link',
            field=models.URLField(help_text='Link a la planilla 080', null=True, verbose_name='Ética presupuestaria / planilla 080'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_172',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_172_link',
            field=models.URLField(help_text='Link a la planilla 172', null=True, verbose_name='Ética presupuestaria / planilla 172'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_exo',
            field=models.BigIntegerField(default=0, help_text='monto total de las exoneraciones de vehículos por concepto de beneficios', verbose_name='Ética presupuestaria / Exoneración'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_exo_link',
            field=models.URLField(help_text='link al documento con el detalle de los montos por exoneración de vehículos', null=True, verbose_name='Ética presupuestaria / Link a Exoneración'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_trav_N',
            field=models.IntegerField(default=0, help_text='Número de viajes realizados por concepto de beneficios.', verbose_name='Ética presupuestaria / Número de viajes'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_trav_exp',
            field=models.BigIntegerField(default=0, help_text='Monto gastado en viáticos en viajes realizados por concepto de beneficios.', verbose_name='Ética presupuestaria / Dinero gastado en viajes'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_trav_link',
            field=models.URLField(null=True, verbose_name='Link al documento con el detalle de número y viáticos en viajes'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.CharField(max_length=255, null=True, verbose_name='Partido'),
        ),
        migrations.AddField(
            model_name='person',
            name='period',
            field=models.CharField(max_length=255, null=True, verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='person',
            name='reelection',
            field=models.BooleanField(default=False, null=True, verbose_name='¿Va a reelección?'),
        ),
        migrations.AddField(
            model_name='person',
            name='web',
            field=models.URLField(null=True, verbose_name='Página web personal'),
        ),
        migrations.AddField(
            model_name='person',
            name='wor_attendance',
            field=models.FloatField(default=0, help_text='porcentaje de asistencia a la Asamblea en el período', verbose_name='Trabajo legislativo / Asistencia'),
        ),
        migrations.AddField(
            model_name='person',
            name='wor_proposals',
            field=models.IntegerField(default=0, help_text='número de propuestas (de discusión, proyectos de ley, etc) realizadas durante el período', verbose_name='Trabajo legislativo / Propuestas'),
        ),
        migrations.AddField(
            model_name='person',
            name='wor_vote',
            field=models.IntegerField(default=0, help_text='número de participaciones en votaciones durante el último período', verbose_name='Trabajo legislativo / Votaciones'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='specific_type',
            field=models.CharField(choices=[('parlamentario', 'Parlamentario'), ('candidato', 'Candidato')], help_text='Parlamentario o candidato', max_length=255, verbose_name='Tipo de persona'),
        ),
    ]
