# Generated by Django 2.1.4 on 2019-01-08 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='benefits',
            field=models.ManyToManyField(to='indice_transparencia.Benefit'),
        ),
        migrations.AlterField(
            model_name='person',
            name='benefits_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Por favor, indique dónde es posible acceder al detalle sobre los valores asociados al uso de beneficios (se le sugiere indicar un link donde esté publicado el detalle)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='circuit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Circuito al que representa o busca representar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='declared_intention_to_transparent',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. transparentar su información política general?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico de contacto'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_080_doc',
            field=models.FileField(blank=True, help_text='Link a la planilla 080', null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name='Si su planilla 080 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_080_link',
            field=models.URLField(blank=True, help_text='Link a la planilla 080', null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 080'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_172_doc',
            field=models.FileField(blank=True, help_text='Link a la planilla 172', null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name='Si su planilla 172 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_172_link',
            field=models.URLField(blank=True, help_text='Link a la planilla 172', null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 172'),
        ),
        migrations.AlterField(
            model_name='person',
            name='existing_interests_declaration',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Cuenta ud. con una declaración de intereses actualizada?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_education',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='¿Desea transparentar alguna otra experiencia relevante de formación? Puede escribirlas a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_judiciary_declaration',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='¿Se ha visto involucrado en más procesos judiciales?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='intention_to_transparent_patrimony',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Desea Ud. transparentar sus declaraciones de Patrimonio e Intereses'),
        ),
        migrations.AlterField(
            model_name='person',
            name='intention_to_transparent_work_plan',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. transparentar su plan de trabajo de diputado(a) o candidato(a)?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interests_doc',
            field=models.FileField(blank=True, null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name="Si respondió 'sí' pero no tiene su declaración de intereses publicada online, acá tiene la oportunidad de adjuntar el archivo"),
        ),
        migrations.AlterField(
            model_name='person',
            name='interests_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Si respondió 'sí' por favor indique a continuación el link para acceder a su declaración de Intereses"),
        ),
        migrations.AlterField(
            model_name='person',
            name='judiciary_declaration',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. transparentar información sobre los procesos judiciales en los que ha estado involucrado(a)?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='judiciary_description',
            field=models.TextField(blank=True, null=True, verbose_name='¿Desea agregar comentarios o notas aclaratorias sobre uno o más de los procesos judiciales declarados?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='judiciary_link',
            field=models.URLField(blank=True, null=True, verbose_name="Si respondió 'sí', por favor indique dónde se puede acceder a esta información (facilite un link u otro recurso)"),
        ),
        migrations.AlterField(
            model_name='person',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='indice_transparencia.Party'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patrimony_doc',
            field=models.FileField(blank=True, null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name="Si respondió 'sí' pero no tiene su declaración de patrimonio publicada online, acá tiene la oportunidad de adjuntar el archivo"),
        ),
        migrations.AlterField(
            model_name='person',
            name='patrimony_link',
            field=models.URLField(blank=True, null=True, verbose_name="Si respondió 'sí' por favor indique a continuación el link para acceder a su declaración de patrimonio"),
        ),
        migrations.AlterField(
            model_name='person',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿En qué período legislativo se encuentra actualmente?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='previous_parties',
            field=models.ManyToManyField(blank=True, related_name='ex_members', to='indice_transparencia.Party', verbose_name='¿Ha pertenecido ud. a otros partidos o movimientos políticos?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reelection',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Eres actualmente diputado/a?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='web',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Link al sitio web personal (o cuenta oficial en redes sociales)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_plan_doc',
            field=models.FileField(blank=True, null=True, upload_to='work_plans/%Y/%m/%d/', verbose_name="Si respondió 'sí' pero no tiene su plan de trabajo online, acá tiene la posibilidad de adjuntar el archivo"),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_plan_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name="Si respondió 'sí', indique en qué link se puede acceder a su programa de trabajo"),
        ),
    ]
