# Generated by Django 2.1.4 on 2019-01-09 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0002_auto_20190108_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='indice_transparencia.Benefit'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='indice_transparencia.Person'),
        ),
    ]
