# Generated by Django 2.1.4 on 2019-01-10 14:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0003_auto_20190109_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
    ]
