# Generated by Django 2.1.4 on 2019-01-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0006_auto_20190116_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='indice_transparencia.Circuit', verbose_name='Circuito al que representa o busca representar'),
        ),
    ]
