# Generated by Django 2.1.4 on 2019-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0007_auto_20190116_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='district',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Distritos'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='province',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
    ]
