# Generated by Django 2.1.4 on 2019-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0008_auto_20190116_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Distritos'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='province',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Provincia'),
        ),
    ]
