# Generated by Django 2.1.4 on 2019-01-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0009_auto_20190116_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='judiciary_declaration',
        ),
        migrations.RemoveField(
            model_name='person',
            name='specific_type',
        ),
        migrations.AddField(
            model_name='person',
            name='attendance',
            field=models.FloatField(blank=True, null=True, verbose_name='Indique su porcentaje de asistencia a la Asamblea Nacional durante este período legislativo'),
        ),
        migrations.AddField(
            model_name='person',
            name='benefits_doc',
            field=models.FileField(blank=True, null=True, upload_to='benefits/%Y/%m/%d/', verbose_name='Si el detalle de su uso de beneficios no se encuentra publicado online, puede subir el archivo a continuación'),
        ),
        migrations.AddField(
            model_name='person',
            name='declared_intention_to_transparent_education',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. compartir información sobre su formación/educación?'),
        ),
        migrations.AddField(
            model_name='person',
            name='declared_intention_to_transparent_judiciary_records',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. compartir información sobre los procesos judiciales en los que ha estado involucrado(a)?'),
        ),
        migrations.AddField(
            model_name='person',
            name='declared_intention_to_transparent_political_profile',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. compartir información sobre sus afiliaciones políticas?'),
        ),
        migrations.AddField(
            model_name='person',
            name='declared_intention_to_transparent_political_proposal',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. compartir su propuesta política de diputado(a) o candidato(a)?'),
        ),
        migrations.AddField(
            model_name='person',
            name='declared_intention_to_transparent_public_resources_usage',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. compartir información sobre su uso de recursos públicos?'),
        ),
        migrations.AddField(
            model_name='person',
            name='declared_intention_to_transparent_work',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. compartir información sobre su experiencia laboral?'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_001_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_001/%Y/%m/%d/', verbose_name='Si su planilla 001 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_001_link',
            field=models.URLField(blank=True, help_text='Link a la planilla 001', null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 001'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_002_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_002/%Y/%m/%d/', verbose_name='Si su planilla 002 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AddField(
            model_name='person',
            name='eth_002_link',
            field=models.URLField(blank=True, help_text='Link a la planilla 002', null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 002'),
        ),
        migrations.AddField(
            model_name='person',
            name='existing_patrimony_declaration',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Cuenta ud. con una declaración de intereses actualizada?'),
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Cuenta de facebook'),
        ),
        migrations.AddField(
            model_name='person',
            name='has_changed_party',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Ha pertenecido ud. a otros partidos o movimientos políticos?'),
        ),
        migrations.AddField(
            model_name='person',
            name='has_political_proposal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ya sea diputado(a) o candidato(a), ¿Cuenta ud. con una propuesta política para su gestión (2019-2024)?'),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Cuenta de instagram'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deputy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Eres actualmente diputado/a?'),
        ),
        migrations.AddField(
            model_name='person',
            name='judiciary_processes_involved',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿En cuántos procesos judiciales ud. se ha visto involucrado en los últimos 10 años?'),
        ),
        migrations.AddField(
            model_name='person',
            name='laws_worked_on',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indique el número de leyes que ud. ha sancionado en el último período legislativo'),
        ),
        migrations.AddField(
            model_name='person',
            name='political_proposal_doc',
            field=models.FileField(blank=True, null=True, upload_to='political_proposals/%Y/%m/%d/', verbose_name='Si respondió "sí" pero no tiene su propuesta política online, acá tiene la posibilidad de adjuntar el archivo'),
        ),
        migrations.AddField(
            model_name='person',
            name='political_proposal_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Si respondió "sí", indique en qué link se puede acceder a su propuesta política'),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Cuenta de twitter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='benefits_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Por favor, indique en qué link es posible acceder al detalle sobre los montos asociados a su uso de beneficios'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_080_doc',
            field=models.FileField(blank=True, help_text='Link a la planilla 080', null=True, upload_to='eth_080/%Y/%m/%d/', verbose_name='Si su planilla 080 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_172_doc',
            field=models.FileField(blank=True, help_text='Link a la planilla 172', null=True, upload_to='eth_172/%Y/%m/%d/', verbose_name='Si su planilla 172 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_education',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='¿Desea compartir alguna otra experiencia relevante de formación? Puede escribirlas a continuación:'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_judiciary_declaration',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='¿Se ha visto involucrado en más procesos judiciales en los últimos 10 años?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='intention_to_transparent_patrimony',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Desea Ud. compartir sus declaraciones de Patrimonio e Intereses'),
        ),
        migrations.AlterField(
            model_name='person',
            name='judiciary_description',
            field=models.TextField(blank=True, null=True, verbose_name='¿Desea agregar comentarios o notas aclaratorias sobre uno o más de los procesos judiciales declarados? Puede hacerlo a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='previous_parties',
            field=models.ManyToManyField(blank=True, related_name='ex_members', to='indice_transparencia.Party', verbose_name='Si respondió "sí", seleccione a qué otros partidos ha pertenecido en el pasado'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reelection',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Va a reelección?'),
        ),
    ]
