# Generated by Django 2.1.5 on 2019-01-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0012_party_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Beneficio'},
        ),
        migrations.AlterModelOptions(
            name='circuit',
            options={'verbose_name': 'Circuito'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Partido'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Tema Prioritario'},
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_001_link',
            field=models.URLField(blank=True, null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 001'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_002_link',
            field=models.URLField(blank=True, null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 002'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_080_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_080/%Y/%m/%d/', verbose_name='Si su planilla 080 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_172_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_172/%Y/%m/%d/', verbose_name='Si su planilla 172 no se encuentra publicada online, puede subir el archivo a continuación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='existing_patrimony_declaration',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Cuenta ud. con una declaración de patrimonio actualizada?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='has_political_proposal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ya sea diputado(a) o candidato(a), ¿Cuenta ud. con una propuesta política para su gestión (2019-2024)?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='intention_to_transparent_patrimony',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Desea Ud. compartir sus declaraciones de Patrimonio e Intereses'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interests_doc',
            field=models.FileField(blank=True, null=True, upload_to='interests/%Y/%m/%d/', verbose_name='Si no tiene su declaración de intereses, en esta url ( http://bit.ly/indiceint) puede descargar un formato para crearla y luego cargarla acá:)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patrimony_doc',
            field=models.FileField(blank=True, null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name='Si no tiene su declaración de patrimonio, en esta url ( http://bit.ly/indicepat) puede descargar un formato para crearla y luego cargarla acá:)'),
        ),
    ]
