# Generated by Django 2.1.5 on 2019-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0013_auto_20190123_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='eth_080_link',
            field=models.URLField(blank=True, null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 080'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_172_link',
            field=models.URLField(blank=True, null=True, verbose_name='Indique en qué link es posible acceder al detalle de su planilla 172'),
        ),
    ]
