# Generated by Django 2.1.5 on 2019-01-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0014_auto_20190123_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='intention_to_transparent_work_plan',
        ),
        migrations.RemoveField(
            model_name='person',
            name='work_plan_doc',
        ),
        migrations.RemoveField(
            model_name='person',
            name='work_plan_link',
        ),
    ]
