# Generated by Django 2.1.5 on 2019-01-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0015_auto_20190123_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ranking_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
