# Generated by Django 2.1.5 on 2019-01-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0015_auto_20190123_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='other_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro tema prioritario'),
        ),
    ]
