# Generated by Django 2.1.5 on 2019-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0016_person_ranking_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position_in_ranking',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
