# Generated by Django 2.1.5 on 2019-01-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0016_person_other_topic'),
        ('indice_transparencia', '0016_person_ranking_mark'),
    ]

    operations = [
    ]
