# Generated by Django 2.1.5 on 2019-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0017_person_position_in_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='other_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro tema prioritario'),
        ),
    ]
