# Generated by Django 2.1.5 on 2019-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0018_person_other_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='benefits_doc',
            field=models.FileField(blank=True, null=True, upload_to='benefits/%Y/%m/%d/', verbose_name='Subir beneficios'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_001_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_001/%Y/%m/%d/', verbose_name='Subir planilla 001'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_002_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_002/%Y/%m/%d/', verbose_name='Subir planilla 002'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_080_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_080/%Y/%m/%d/', verbose_name='Subir planilla 080'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_172_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_172/%Y/%m/%d/', verbose_name='Subir planilla 172'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/%d/', verbose_name='Subir foto'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interests_doc',
            field=models.FileField(blank=True, null=True, upload_to='interests/%Y/%m/%d/', verbose_name='Subir declaración intereses'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patrimony_doc',
            field=models.FileField(blank=True, null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name='Subir declaración de patrimonio'),
        ),
        migrations.AlterField(
            model_name='person',
            name='political_proposal_doc',
            field=models.FileField(blank=True, null=True, upload_to='political_proposals/%Y/%m/%d/', verbose_name='Adjuntar archivo propuesta política'),
        ),
    ]
