# Generated by Django 2.1.5 on 2019-01-30 13:53

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0019_auto_20190130_1329'),## Eso!!
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='volunteer_changed',
            field=picklefield.fields.PickledObjectField(default=list, editable=False),
        ),
    ]
