# Generated by Django 2.1.5 on 2019-01-31 14:29

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0020_person_volunteer_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
    ]
