# Generated by Django 2.1.5 on 2019-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0020_person_volunteer_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='person_set', to='indice_transparencia.Topic', verbose_name='Por favor indique los tres temas o problemáticas en las que le gustaría enfocarse durante su gestión (2019-2024).'),
        ),
    ]
