# Generated by Django 2.1.5 on 2019-01-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0021_auto_20190131_1429'),
        ('indice_transparencia', '0021_auto_20190131_1818'),
    ]

    operations = [
    ]
