# Generated by Django 2.1.5 on 2019-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice_transparencia', '0023_auto_20190205_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='benefits_doc',
            field=models.FileField(blank=True, null=True, upload_to='benefits/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_001_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_001/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_002_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_002/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_080_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_080/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='eth_172_doc',
            field=models.FileField(blank=True, null=True, upload_to='eth_172/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='interests_doc',
            field=models.FileField(blank=True, null=True, upload_to='interests/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='patrimony_doc',
            field=models.FileField(blank=True, null=True, upload_to='patrimony/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='political_proposal_doc',
            field=models.FileField(blank=True, null=True, upload_to='political_proposals/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='previous_parties',
            field=models.ManyToManyField(blank=True, related_name='ex_members', to='indice_transparencia.Party', verbose_name='Si respondió "sí", seleccione a qué otros partidos ha pertenecido en el pasado. Mantener “Control” o “Command” (en Mac) para seleccionar más de una opción.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='person_set', to='indice_transparencia.Topic', verbose_name='Por favor indique los tres temas o problemáticas en las que le gustaría enfocarse durante su gestión (2019-2024). Mantener “Control” o “Command” (en Mac) para seleccionar más de una opción.'),
        ),
    ]
